- hosts: all
  gather_facts: no
  tasks:
    - name: Copy WAR to Tomcat
      copy:
        src: /var/lib/jenkins/workspace/Ansi_Jenkins_Sonar/Amazon-Web/target/Amazon.war
        dest: /home/rahul/Batch11/Ansi_Jenkins_Sonar/Tomcat/apache-tomcat-9.0.106/webapps
        mode: '0644'
        remote_src: yes

    - name: Make Tomcat startup script executable
      file:
        path: "/home/rahul/Batch11/Ansi_Jenkins_Sonar/Tomcat/apache-tomcat-9.0.106/bin/startup.sh"
        mode: '0755'

    - name: Start Tomcat
      shell: /home/rahul/Batch11/Ansi_Jenkins_Sonar/Tomcat/apache-tomcat-9.0.106/bin/startup.sh
